import type { Metadata } from "next";
import { K2D } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/Navigation";

const k2d = K2D({ subsets: ["latin"], weight:["200", "300", "400"] });

export const metadata: Metadata = {
  title: "Oscar Reyes",
  description: "Oscar Reyes's Portfolio generated by Next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={k2d.className}>
        <main className="bg-background">
          {children}
        </main>
        
        
      </body>
    </html>
  );
}
